### ISSUE TITLE
multi-language support 

### ISSUE THREAD

**Issue by wanghaisheng** [OHDSI/TheBookOfOhdsi#23]
for example how to translate contents into chinese ,spanish?
is the best practise to fork another repo?
since the content is continuing to change

**Comment by schuemie** [comment]
Good question! I don't know the right answer.

A fork might help you keep all non-language-specific artifacts (like images) synchronized, while allowing you to build the book to a different website. But it would be annoying to have the different language versions in the RMarkdown files. Maybe I should place all English markdown files in an 'English' subfolder, so everyone can create their own language folders?

As for the continuously changing content: I was imagining we do work with 'editions'. Hopefully for the symposium in September we'll have our 1st edition, which will be a Git tag in the repo, and also the version that will go to the printer. The online version will keep being updated after that, but the 1st edition will be static. At some point we'll create a new edition, and so on.

Maybe those editions should be the focus of the translations? That would mean you're lagging behind the online version though...

Pulling in @chandryou, who is working on the Korean version.

**Comment by chandryou** [comment]
Currently, I'm working in [The Book Of OHDSI Korea repo](https://github.com/ohdsi-korea/TheBookOfOhdsiKorea) in the [Korean OHDSI repo](https://github.com/ohdsi-korea).
You can see the draft: https://ohdsi-korea.github.io/TheBookOfOhdsiKorea/

I added chapters for the history of OHDSI in Korea and reproducible research. 

I think OHDSI book in other languages should be managed independently, because the original ohdsi book will be updated and each country can have their own specific themes for the book.
